### ISSUE TITLE
width, height attributes

### ISSUE THREAD

**Issue by neapel** [betamax/getImageData#1]
Is there a good reason for setting width and height of the image from JSON? At this point it'll only take very shortly until the browser has parsed the size. So there wouldn't be a need to have imagemagick on the server, which should reduce load a bit.

**Comment by betamax** [comment]
Sorry, this is an old issue but have only just seen it. The width and height could be used for many different reasons so therefore I think it's useful to include. You're right that it can be got in the browser but the reason it is included is so that you can use `canvas.drawImage` 'out of the box' without the need for load events on the image or things like that. There's probably other usage instances that require a width and height but I think it's worth keeping it in the plugin/server code (especially on Google App Engine).

Could also potentially add it in as a server parameter & plugin option to request width and height?
