### ISSUE TITLE
TypeError: O is undefined

### ISSUE THREAD

**Issue by thehans** [betamax/getImageData#10]
Attempting to run the first example listed on your site verbatim: http://www.maxnov.com/getimagedata/

results in a "TypeError: O is undefined"
on line 27 of https://rawgithub.com/betamax/getImageData/master/jquery.getimagedata.js

http://jsfiddle.net/27hXw/

**Comment by thehans** [comment]
I just did some more testing and found that it was due to the version of jquery i was including.  It appears that compatibility is broken somewhere between jQuery version 1.8.3 and 1.9.1.

**Comment by rhernandog** [comment]
Hi,

The problem is in the jsonp plugin. To solve this you need to replace the one in get image data with the newest version, which you can find here:

https://github.com/jaubourg/jquery-jsonp/blob/master/src/jquery.jsonp.js

Just a simple copy paste. A good suggestion is to compress and then replace, no need to add the production code.

Rodrigo.

**Comment by betamax** [comment]
Thanks @rhernandog and @thehans :+1:
