### ISSUE TITLE
503 errors on img-to-json

### ISSUE THREAD

**Issue by b1kjsh** [betamax/getImageData#13]
It looks like the appspot site used for img-to-json is no longer operational...
http://puu.sh/8lNIO.png

**Comment by betamax** [comment]
This is because the appspot site is a Google App Engine project on the free tier. I don't pay for it because of the fact it's public and could be abused. If you look at the documentation there is a section called 'Using your own server' which explains that you can set up your own server that will avoid this: http://www.maxnov.com/getimagedata/#using-your-own-server

**Comment by b1kjsh** [comment]
Oh I see! I apologize I should have paid more attention to the document.

Josh Howard
435-535-1573
